# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DORuPMbF520RgsJUd4dP9wNOApZC2yck
"""

!pip install -q groq streamlit

from google.colab import userdata

groq_api_key = userdata.get("GROQ_API_KEY")

print("API key loaded:", groq_api_key is not None)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile prompt.py
# 
# def create_email_prompt(
#     recipient,
#     purpose,
#     topic,
#     key_points,
#     tone,
#     length
# ):
#     prompt = f"""
# You are an intelligent and professional AI email writing assistant.
# 
# Your task is to generate a high-quality email based on the user's
# requirements.
# 
# USER REQUIREMENTS
# ----------------
# 
# Recipient:
# {recipient}
# 
# Purpose:
# {purpose}
# 
# Topic:
# {topic}
# 
# Key Points:
# {key_points}
# 
# Tone:
# {tone}
# 
# Desired Length:
# {length}
# 
# 
# INSTRUCTIONS
# ------------
# 
# 1. Write a complete email based on the information provided.
# 2. Generate a clear and concise subject line.
# 3. Include an appropriate greeting.
# 4. Include all important key points.
# 5. Match the requested tone.
# 6. Match the requested length.
# 7. Use natural human-like language.
# 8. Use correct grammar and spelling.
# 9. Do not invent facts, names, dates, numbers, or other information.
# 10. Do not mention that you are an AI.
# 11. Do not explain your reasoning or writing process.
# 12. Return only the finished email.
# 
# 
# OUTPUT FORMAT
# -------------
# 
# Subject: [Email Subject]
# 
# [Greeting]
# 
# [Email Body]
# 
# [Closing]
# 
# Do not add any explanation before or after the email.
# """
# 
#     return prompt

# Commented out IPython magic to ensure Python compatibility.
# %%writefile email_generator.py
# 
# from groq import Groq
# from prompt import create_email_prompt
# 
# 
# MODEL_NAME = "openai/gpt-oss-120b"
# 
# 
# def generate_email(
#     api_key,
#     recipient,
#     purpose,
#     topic,
#     key_points,
#     tone,
#     length
# ):
#     if not api_key:
#         raise ValueError("Groq API key is missing.")
# 
#     client = Groq(api_key=api_key)
# 
#     prompt = create_email_prompt(
#         recipient=recipient,
#         purpose=purpose,
#         topic=topic,
#         key_points=key_points,
#         tone=tone,
#         length=length
#     )
# 
#     response = client.chat.completions.create(
#         model=MODEL_NAME,
#         messages=[
#             {
#                 "role": "system",
#                 "content": (
#                     "You are an expert professional email writing "
#                     "assistant. Generate natural, clear, accurate, "
#                     "and context-appropriate emails."
#                 )
#             },
#             {
#                 "role": "user",
#                 "content": prompt
#             }
#         ],
#         temperature=0.7,
#         max_tokens=800
#     )
# 
#     generated_email = response.choices[0].message.content
# 
#     return generated_email.strip()

from email_generator import generate_email

email = generate_email(
    api_key=groq_api_key,
    recipient="Professor",
    purpose="Request",
    topic="Assignment extension",
    key_points=(
        "I need two extra days to complete my assignment "
        "because I need more time to research the topic."
    ),
    tone="Polite and professional",
    length="Medium"
)

print(email)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# from email_generator import generate_email
# 
# 
# st.set_page_config(
#     page_title="AI Email Generator",
#     page_icon="✉️",
#     layout="centered"
# )
# 
# 
# st.markdown(
#     """
#     <style>
# 
#     .main {
#         padding-top: 2rem;
#     }
# 
#     .title {
#         text-align: center;
#         font-size: 42px;
#         font-weight: 700;
#         margin-bottom: 5px;
#     }
# 
#     .subtitle {
#         text-align: center;
#         color: #6b7280;
#         font-size: 17px;
#         margin-bottom: 30px;
#     }
# 
#     .email-header {
#         font-size: 22px;
#         font-weight: 600;
#         margin-top: 30px;
#         margin-bottom: 10px;
#     }
# 
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# 
# st.markdown(
#     '<div class="title">✉️ AI Email Generator</div>',
#     unsafe_allow_html=True
# )
# 
# st.markdown(
#     '<div class="subtitle">'
#     'Generate professional emails in seconds using AI'
#     '</div>',
#     unsafe_allow_html=True
# )
# 
# 
# try:
#     GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
# 
# except KeyError:
#     st.error(
#         "GROQ_API_KEY is not configured. "
#         "Please add it to your Streamlit Secrets."
#     )
#     st.stop()
# 
# 
# st.subheader("📝 Email Details")
# 
# 
# recipient = st.text_input(
#     "Recipient",
#     placeholder="e.g. Professor, Manager, Client"
# )
# 
# 
# purpose = st.selectbox(
#     "Purpose",
#     [
#         "Request",
#         "Thank You",
#         "Follow Up",
#         "Apology",
#         "Introduction",
#         "Meeting",
#         "Application",
#         "Complaint",
#         "Other"
#     ]
# )
# 
# 
# topic = st.text_input(
#     "Email Topic",
#     placeholder="e.g. Request for assignment extension"
# )
# 
# 
# key_points = st.text_area(
#     "Key Points",
#     placeholder=(
#         "Enter the important information you want "
#         "to include in the email..."
#     ),
#     height=150
# )
# 
# 
# col1, col2 = st.columns(2)
# 
# 
# with col1:
#     tone = st.selectbox(
#         "Tone",
#         [
#             "Professional",
#             "Friendly",
#             "Formal",
#             "Casual",
#             "Persuasive"
#         ]
#     )
# 
# 
# with col2:
#     length = st.selectbox(
#         "Length",
#         [
#             "Short",
#             "Medium",
#             "Detailed"
#         ]
#     )
# 
# 
# st.write("")
# 
# 
# generate_button = st.button(
#     "✨ Generate Email",
#     type="primary",
#     use_container_width=True
# )
# 
# 
# if generate_button:
# 
#     if not recipient.strip():
#         st.warning("Please enter the recipient.")
#         st.stop()
# 
#     if not topic.strip():
#         st.warning("Please enter the email topic.")
#         st.stop()
# 
#     if not key_points.strip():
#         st.warning("Please enter the key points.")
#         st.stop()
# 
#     with st.spinner("🤖 Generating your email..."):
# 
#         try:
#             generated_email = generate_email(
#                 api_key=GROQ_API_KEY,
#                 recipient=recipient,
#                 purpose=purpose,
#                 topic=topic,
#                 key_points=key_points,
#                 tone=tone,
#                 length=length
#             )
# 
#             st.session_state["generated_email"] = generated_email
# 
#         except Exception as e:
#             st.error(
#                 f"❌ Failed to generate email: {str(e)}"
#             )
# 
# 
# if "generated_email" in st.session_state:
# 
#     st.markdown(
#         '<div class="email-header">📧 Generated Email</div>',
#         unsafe_allow_html=True
#     )
# 
#     generated_email = st.session_state["generated_email"]
# 
#     st.text_area(
#         "Your generated email",
#         value=generated_email,
#         height=400,
#         key="email_output"
#     )
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.download_button(
#             label="⬇️ Download",
#             data=generated_email,
#             file_name="generated_email.txt",
#             mime="text/plain",
#             use_container_width=True
#         )
# 
#     with col2:
#         if st.button(
#             "🗑️ Clear",
#             use_container_width=True
#         ):
#             del st.session_state["generated_email"]
#             st.rerun()
# 
# 
# st.divider()
# 
# st.caption(
#     "Powered by Groq + GPT • Built with Streamlit"
# )

import os

os.makedirs(".streamlit", exist_ok=True)

with open(".streamlit/secrets.toml", "w") as f:
    f.write(f'GROQ_API_KEY = "{groq_api_key}"\n')

print("Streamlit secret configured.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile .gitignore
# 
# .streamlit/secrets.toml
# __pycache__/
# *.pyc
# .ipynb_checkpoints/
# .env

# Install Cloudflare Tunnel
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb >/dev/null 2>&1

# Stop any previous Streamlit/Cloudflare processes
!pkill -f streamlit || true
!pkill -f cloudflared || true

# Start Streamlit
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 >/tmp/streamlit.log 2>&1 &

# Wait for Streamlit to start
import time
time.sleep(5)

# Start Cloudflare Quick Tunnel
!cloudflared tunnel --url http://127.0.0.1:8501

!find /content -maxdepth 2 -type f | sort